apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freemarket.fullname" . }}-credentials
  labels:
    {{- include "freemarket.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.credentials.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.credentials.postgresPassword | quote }}
  SECURITY_JWT_SECRET: {{ .Values.credentials.jwtSecret | quote }}
