spring.application.name=freemarket-platform

spring.datasource.url=jdbc:postgresql://localhost:5432/freemarket
spring.datasource.username=admin
spring.datasource.password=password

# JPA schema handling
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Server
server.port=8080

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Avoid Spring legacy SQL init (Flyway used instead)
spring.sql.init.mode=never

# Connection pool preferences
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5